version: '3.4'
services:
  postgres-compose:
    image: postgres:13.1
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "meli2021go"
      POSTGRES_DB: "dna"
    ports:
      - "5432:5432"
    restart: always


